export const cityData = [
  { value: 'quezon city', label: 'Quezon City' },
  { value: 'manila', label: 'Manila' },
  { value: 'caloocan', label: 'Caloocan' },
  { value: 'davao city', label: 'Davao City' },
  { value: 'cebu city', label: 'Cebu City' },
  { value: 'zamboanga city', label: 'Zamboanga City' },
  { value: 'taguig city', label: 'Taguig City' },
  { value: 'antipolo city', label: 'Antipolo City' },
  { value: 'pasig city', label: 'Pasig City' },
  { value: 'cagayan de oro city', label: 'Cagayan de Oro City' },
  { value: 'paranaque city', label: 'Paranaque City' },
  { value: 'makati city', label: 'Makati City' },
  { value: 'bacoor', label: 'Bacoor' },
  { value: 'muntinlupa city', label: 'Muntinlupa City' },
  { value: 'iloilo city', label: 'Iloilo City' },
  { value: 'marikina city', label: 'Marikina City' },
  { value: 'valenzuela city', label: 'Valenzuela City' },
  { value: 'las pinas city', label: 'Las Pinas City' },
  { value: 'mandaluyong city', label: 'Mandaluyong City' },
  { value: 'pasay city', label: 'Pasay City' },
  { value: 'angeles city', label: 'Angeles City' },
  { value: 'general santos city', label: 'General Santos City' },
  { value: 'lipa city', label: 'Lipa City' },
  { value: 'lucena city', label: 'Lucena City' },
  { value: 'san juan city', label: 'San Juan City' },
  { value: 'dagupan city', label: 'Dagupan City' },
  { value: 'tacloban city', label: 'Tacloban City' },
  { value: 'olongapo city', label: 'Olongapo City' },
  { value: 'binan', label: 'Biñan' },
  { value: 'imus', label: 'Imus' },
  { value: 'tarlac city', label: 'Tarlac City' },
  { value: 'calamba', label: 'Calamba' },
  { value: 'bacolod city', label: 'Bacolod City' },
  { value: 'iligan city', label: 'Iligan City' },
  { value: 'malolos', label: 'Malolos' },
  { value: 'san fernando city', label: 'San Fernando City' },
  { value: 'santa rosa', label: 'Santa Rosa' },
  { value: 'lapu-lapu city', label: 'Lapu-Lapu City' },
  { value: 'cabanatuan city', label: 'Cabanatuan City' },
  { value: 'butuan city', label: 'Butuan City' },
];

export const regionData = [
  { value: 'Region I', label: 'Region I - Ilocos Region' },
  { value: 'Region II', label: 'Region II - Cagayan Valley' },
  { value: 'Region III', label: 'Region III - Central Luzon' },
  { value: 'Region IV-A', label: 'Region IV-A - CALABARZON' },
  { value: 'Region IV-B', label: 'Region IV-B - MIMAROPA' },
  { value: 'Region V', label: 'Region V - Bicol Region' },
  { value: 'Region VI', label: 'Region VI - Western Visayas' },
  { value: 'Region VII', label: 'Region VII - Central Visayas' },
  { value: 'Region VIII', label: 'Region VIII - Eastern Visayas' },
  { value: 'Region IX', label: 'Region IX - Zamboanga Peninsula' },
  { value: 'Region X', label: 'Region X - Northern Mindanao' },
  { value: 'Region XI', label: 'Region XI - Davao Region' },
  { value: 'Region XII', label: 'Region XII - SOCCSKSARGEN' },
  { value: 'NCR', label: 'NCR - National Capital Region' },
  { value: 'CAR', label: 'CAR - Cordillera Administrative Region' },
  { value: 'CARAGA', label: 'CARAGA' },
];

export const countryData = [
  { value: 'philippines', label: 'Philippines' },
  { value: 'afghanistan', label: 'Afghanistan' },
  { value: 'albania', label: 'Albania' },
  { value: 'algeria', label: 'Algeria' },
  { value: 'andorra', label: 'Andorra' },
  { value: 'angola', label: 'Angola' },
  { value: 'antiguaandbarbuda', label: 'Antigua and Barbuda' },
  { value: 'argentina', label: 'Argentina' },
  { value: 'armenia', label: 'Armenia' },
  { value: 'australia', label: 'Australia' },
  { value: 'austria', label: 'Austria' },
  { value: 'azerbaijan', label: 'Azerbaijan' },
  { value: 'bahamas', label: 'Bahamas' },
  { value: 'bahrain', label: 'Bahrain' },
  { value: 'bangladesh', label: 'Bangladesh' },
  { value: 'barbados', label: 'Barbados' },
  { value: 'belarus', label: 'Belarus' },
  { value: 'belgium', label: 'Belgium' },
  { value: 'belize', label: 'Belize' },
  { value: 'benin', label: 'Benin' },
  { value: 'bhutan', label: 'Bhutan' },
  { value: 'bolivia', label: 'Bolivia' },
  { value: 'bosniaandherzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'botswana', label: 'Botswana' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'brunei', label: 'Brunei' },
  { value: 'bulgaria', label: 'Bulgaria' },
  { value: 'burkinafaso', label: 'Burkina Faso' },
  { value: 'burundi', label: 'Burundi' },
  { value: 'cabo', label: 'Cabo Verde' },
  { value: 'cambodia', label: 'Cambodia' },
  { value: 'cameroon', label: 'Cameroon' },
  { value: 'canada', label: 'Canada' },
  { value: 'centralafricanrepublic', label: 'Central African Republic' },
  { value: 'chad', label: 'Chad' },
  { value: 'chile', label: 'Chile' },
  { value: 'china', label: 'China' },
  { value: 'colombia', label: 'Colombia' },
  { value: 'comoros', label: 'Comoros' },
  { value: 'congo', label: 'Congo' },
];
