export const data = [
  {
    id: 1,
    imageSrc:
      'https://retailminded.com/wp-content/uploads/2016/03/EN_GreenOlive-1.jpg',
    merchant: 'Sample Merchant 1',
    productName: 'Product 1',
    price: 200.0,
    quantity: 4,
  },
  {
    id: 2,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 2',
    productName: 'Product 2',
    price: 150.0,
    quantity: 2,
  },
  {
    id: 3,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 4,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 5,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 6,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 7,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 8,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 9,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 10,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },
  {
    id: 11,
    imageSrc: 'path-to-image-2.jpg',
    merchant: 'Sample Merchant 3',
    productName: 'Product 2',
    price: 250.0,
    quantity: 2,
  },

  // Add more items as needed to test
];
